# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_auto_20180417_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(null=True),
        ),
    ]
